# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ajax01', '0002_auto_20180519_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajax_user',
            name='pwd',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
