# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax01', '0003_ajax_user_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajax_UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='ajax_user',
            old_name='pwd',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ajax_user',
            name='title',
        ),
        migrations.AddField(
            model_name='ajax_user',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
